fullnameOverride: gateway

gateway:
  # startupProbeDelay: 10000
  replicas: 2
  secretRef: gateway-env-vars
  env:
    # Configure connection to Kafka
    KAFKA_BOOTSTRAP_SERVERS: franz-kafka.conduktor.svc.cluster.local:9092
    KAFKA_SASL_MECHANISM: PLAIN
    KAFKA_SECURITY_PROTOCOL: SASL_SSL
    KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/gateway/tls/truststore/kafka.truststore.jks
    # Configure Client -> Gateway
    GATEWAY_SECURITY_PROTOCOL: DELEGATED_SASL_SSL
    GATEWAY_ADVERTISED_HOST: gateway.k8s.orb.local
    GATEWAY_ROUTING_MECHANISM: host
    GATEWAY_ADVERTISED_SNI_PORT: "9092"
    GATEWAY_SNI_HOST_SEPARATOR: "." # e.g. "brokermain0" + "." + "gateway.k8s.orb.local"
    GATEWAY_FEATURE_FLAGS_INTERNAL_LOAD_BALANCING: "false"
    GATEWAY_HTTPS_KEY_STORE_PATH: /etc/gateway/tls/gateway.keystore.jks
    # # Enhanced logging
    # LOG4J2_ORG_APACHE_KAFKA_LEVEL: debug
    # LOG4J2_IO_CONDUKTOR_PROXY_NETWORK_LEVEL: debug
    # LOG4J2_IO_NETTY_LEVEL: debug
  portRange:
    start: 9092
    count: 1
  volumes:
    - name: truststore
      secret:
        secretName: gateway-cert
        items:
        - key: kafka.truststore.jks
          path: kafka.truststore.jks
  volumeMounts:
    - name: truststore
      mountPath: /etc/gateway/tls/truststore/
      readonly: true

tls:
  enable: true
  secretRef: gateway-cert
  keystoreFile: gateway.keystore.jks
  keystoreKey: gateway.keystore.jks

service:
  external:
    enable: true
    type: LoadBalancer
    admin: true